### ISSUE TITLE
Why connect broker after receiving a ApplicationReadyEvent

### ISSUE THREAD

**Issue by fireflies-xlt** [rsocket-routing/rsocket-routing-client#2]
Pushing ApplicationReadyEvent is very late after spirng context
invoked refresh method, in our scenarios, we need to fetch some resource by rsocket, and then init spring bean. Is there a better way to achieve it?

**Comment by spencergibb** [comment]
I no longer believe this is the case since `RoutingRSocketRequester` (or just plain `RSocketRequester`) is created during auto configuration now that RSocketClient is supported in RSocket java 1.1 and spring framework.
